### ISSUE TITLE
Apollo.client.mutate in examples has been moved?

### ISSUE THREAD

**Issue by AlexMoutonNoble** [jeddeloh/rescript-apollo-client#107]
I think I found it at ApolloClient.Bindings.Client.ApolloClient.mutate but guessing thats not the intended way for people to find it?

Thanks
A

**Comment by jeddeloh** [comment]
At some point, I converted everything to records. It makes usage almost 1:1 like javascript. This means you call mutate on your configured client like so:
```
let client = ApolloClient.make(...)

client.mutate(...)
```

The documentation has more: https://reasonml-community.github.io/rescript-apollo-client/docs/mutations#directly-via-the-apollo-client

**Comment by jeddeloh** [comment]
Closing. Please open another issue if this didn't resolve things for you. :)
