### ISSUE TITLE
Move rescript-apollo-client off the reasonml-community org

### ISSUE THREAD

**Issue by ryyppy** [jeddeloh/rescript-apollo-client#110]
Hey @jeddeloh!

As discussed in [this forum post](https://forum.rescript-lang.org/t/github-organization-reasonml-community-rescript-community/1630), we'd like to move active ReScript projects to their respective maintainer's github org to free up the reasonml-community org.

Would it be viable to move the repo to your personal / company github org? That way it's easier to tell if a project is actively maintained, especially if it is backed by a company.

You can then explicitly add contributors later on to keep collaboration going!

Let me know what you think!

cheers

**Comment by jeddeloh** [comment]
@ryyppy Thanks for following up on this! It is probably best to transfer back to my personal github for the moment.

**Comment by ryyppy** [comment]
Sounds good! I guess i need to grant you admin rights for this org to move the repo? Let me know if you don't have enough credentials.

**Comment by jeddeloh** [comment]
All done. Thanks!
