### ISSUE TITLE
MockedProvider bindings

### ISSUE THREAD

**Issue by Arnarkari93** [jeddeloh/rescript-apollo-client#112]
How would we approach writing bindings for `MockedProvider`? The `mocks` prop is so dynamic and I am struggling where to begin. Has anybody thought about this?

**Comment by jeddeloh** [comment]
Hey, sorry for the slow reply. I'll take a look at this soon, but before I do, have you considered just writing a simple binding typed in the way you use it rather than trying to represent all the dynamic props?

**Comment by Arnarkari93** [comment]
Isn't going to be an issue that rescript Apollo client is extended and defines a method `rescript_query`? I can't just make a simple binding for mockedProvider and say it is `ApolloClient.t`

**Comment by Arnarkari93** [comment]
Sorry for the late response. Yes, I think recreating it in rescript is a good solution. I don't think I will be working with this library anytime soon, but If I do, I will check it out.
