### ISSUE TITLE
nextFetchPolicy prop missing from QueryHookOptions

### ISSUE THREAD

**Issue by jovanbaj** [jeddeloh/rescript-apollo-client#115]
Is there any particular reason that this prop is missing from the binding?

Detailed explanation of it's usage can be found here:
https://github.com/apollographql/apollo-client/issues/6760#issuecomment-668188727

From the apollographql docs:
https://www.apollographql.com/docs/react/api/react/hooks/#nextfetchpolicy

**Comment by jeddeloh** [comment]
None at all. If it's in the typescript definitions, it should be in here :)

**Comment by jovanbaj** [comment]
Thank you for quick response.
It is there:
https://github.com/apollographql/apollo-client/blob/917dd52893e1bf485e37f5b9fe86787c6066b956/src/react/types/types.ts#L37

**Comment by jeddeloh** [comment]
Great. It looks like a trivial addition. I will get to this at some point, I just don't know when. If you want to take a stab at a PR, it would be most welcome.

**Comment by jeddeloh** [comment]
As of #120, this should now be available on `rescript-apollo-client@dev` and will be in the next release.
