### ISSUE TITLE
Link headers

### ISSUE THREAD

**Issue by dkrukouski** [jeddeloh/rescript-apollo-client#117]
Hello.
I have issue with `HttpLink` headers.

Using this example from the [documentation](https://jeddeloh.github.io/rescript-apollo-client/docs/client-configuration#advanced-typical-configuration), I created a link to my GraphQL endpoint.

```
let httpLink = ApolloClient.Link.HttpLink.make(
  ~uri=_ => Env.graphqlEndpoint,
  ~headers=Obj.magic({"Accept": "application/json"}),
  (),
)
```

I expect the `Accept` header to be exactly `application/json`, but `*/*` is automatically added to the value.
![image](https://user-images.githubusercontent.com/11198493/124288202-9434e980-db59-11eb-8b0a-66595d4a40b2.png)

This is a bug? If not, how can this be fixed?

Thank you!

**Comment by jeddeloh** [comment]
I think this is actually a question for Apollo Client, not this library. We just provide some types and integration with `graphql-ppx` other headers are working normally. That said, I googled for examples and only ever see people using lowercase `accept`. It's a long shot, but have you tried this?

**Comment by dkrukouski** [comment]
@jeddeloh  thanks for your reply

This is very strange, but it works! Thank you! 

I close this issue.
