### ISSUE TITLE
@apollo/client 3.5 features

### ISSUE THREAD

**Issue by illusionalsagacity** [jeddeloh/rescript-apollo-client#137]
https://github.com/apollographql/apollo-client/blob/main/CHANGELOG.md#apollo-client-350-2021-11-08

- [ ] `DataProxy.updateFragment` method
- [ ] `DataProxy.updateQuery` method
- [ ] `MutationResult.reset` method
- [ ] `useLazyQuery` execute function returns a Promise with query result

I think if the minimum version gets bumped to `^3.5.0` that'd require a major version release? The `useLazyQuery` change certainly is breaking.

I'm noticing some commented out `variables` properties in `src/@apollo/client/cache/core/types/ApolloClient__Cache_Core_Types_DataProxy.res`, is this comment

```
// I think fragment variables are still experimental?
```

referring to graphql-ppx or apollo/client?

**Comment by jeddeloh** [comment]
> I think if the minimum version gets bumped to ^3.5.0 that'd require a major version release? The useLazyQuery change certainly is breaking.

Yeah, it's a bit unfortunate that inconsequential changes in JS result in breaking changes here, but what can you do. Apollo also swapped out a type that is a breaking change as well #128. It may be worth looping that in as well.

> I'm noticing some commented out variables properties in src/@apollo/client/cache/core/types/ApolloClient__Cache_Core_Types_DataProxy.res, is this comment `// I think fragment variables are still experimental?` referring to graphql-ppx or apollo/client?

I don't remember at the time what all was experimental. I recall you had to import something from `graphql-tag`? And it wasn't implemented in graphql-ppx I don't think. I don't know what the status is now on graphql-ppx, but if it supports it, yeah, let's get that back in.
