### ISSUE TITLE
Fetching fragment along with other fields

### ISSUE THREAD

**Issue by Arnarkari93** [jeddeloh/rescript-apollo-client#139]
I'm facing an issue when trying to fetch a fragment alongside other fields of the same type. In the [graphql-pxx docs](https://beta.graphql-ppx.com/docs/fragment) there is this example:
```
query UserQuery {
    user {
      id
      role
      ...Avatar_User
    }
}
```
When I try to create a similar query I get an error saying that the `GraphQL_PPX` module is not found. I tried to add a `open ApolloClient` in the same module as I define the query and then I get a different error, saying the the `deepMerge` method is not defined under `GraphQL_PPX`.

**Versions:**
```json
"@apollo/client": "^3.5.7", 
"@reasonml-community/graphql-ppx": "1.2.2",
"graphql": "^16.2.0",
"rescript-apollo-client": "2.4.1",
```

**Reproduce example**: https://github.com/Arnarkari93/fragment-reproduce-issue

**Comment by jfrolich** [comment]
You need to include `@reasonml-community/graphql-ppx` in `bs-dependencies` of `bsconfig.json`
