### ISSUE TITLE
How do I use the InMemoryCache's FieldMergeFunction?

### ISSUE THREAD

**Issue by dfalling** [jeddeloh/rescript-apollo-client#143]
I've dug through the code and haven't found a way to use this merge function.
https://github.com/jeddeloh/rescript-apollo-client/blob/7b167c5d0647f1d479246e04c49e39636ae8bfb4/src/%40apollo/client/cache/inmemory/ApolloClient__Cache_InMemory_Policies_FieldPolicy.res#L7-L12

Apollo's documentation suggests the merge field can take either `true`, to make Apollo handle it, or a function with signature `(existing: 't, incoming: 't) => 't`. Regardless of what I try to assign to this field, I get an error that it doesn't match the expected type.

**Comment by jeddeloh** [comment]
So that `type t` is abstract because the types are unimplemented. You can either cast your field merge function like so:
```
let myMergeFunction: FieldMergeFunction.t = Obj.magic((existing, incoming) => { ... })
```
or you could make a PR to flesh out the types :)

**Comment by dfalling** [comment]
Perfect- that did the trick! Thank you!

I'd love to PR to help, but the type of this is beyond my understanding... I'm not sure how have a union type of a function and `true` that resolve to JS.
```ocaml
module FieldMergeFunction = {
  type t<'existing> =
    | Function(('existing, 'existing) => 'existing)
    | True
}
```

**Comment by dfalling** [comment]
Perfect, thank you! I'll close out this issue and push a WIP PR when I get stumped. Thanks!
