### ISSUE TITLE
support to nextjs ?

### ISSUE THREAD

**Issue by enieber** [jeddeloh/rescript-apollo-client#145]
Hi, this project is very nice, I starting with rescript and graphql with this lib and no has any error, but when I transfer this application to nextjs I found some errors:

Error: Unable to find native implementation, or alternative implementa

![Screenshot error](https://user-images.githubusercontent.com/7907068/189492670-bd1d4ac0-efbf-4162-a624-e93cb109893c.png)
tion for WebSocket!

the project sample nextjs [is open source](https://github.com/station-work/hagrid)

Do I need to change any settings?

**Comment by jeddeloh** [comment]
I think WebSocketLink needs to be run in a browser environment, so if you're doing SSR in Next, Websocket won't be available. You'll need to do some extra checks when configuring your Apollo Client. I did a quick google search and this looks relevant to your situation: https://github.com/apollographql/subscriptions-transport-ws/issues/333#issuecomment-359261024

**Comment by enieber** [comment]
I removed the websocket config, thanks
