### ISSUE TITLE
Support rescript 10

### ISSUE THREAD

**Issue by salemkode** [jeddeloh/rescript-apollo-client#149]

**Comment by jeddeloh** [comment]
Is there something specific that's not working on 10 or do we just need to update our dependencies?

**Comment by illusionalsagacity** [comment]
I believe this was a `peerDependencies` thing, `graphql-ppx` also hasn't been published to show it supports 10 yet, but it does work.

**Comment by jeddeloh** [comment]
Resolved (at least to the extent we can) by #150
