### ISSUE TITLE
fetchMore executing request multiple times

### ISSUE THREAD

**Issue by Laegel** [jeddeloh/rescript-apollo-client#88]
Hey there, first I'd like to thank everybody working on this wonderful library! Combined to GraphQL PPX, it's delightful.

I ran into the following issue: `fetchMore` executes a request multiple times (twice on my project even on simple requests not implying variables or specific stuff and four times on your own example: https://github.com/reasonml-community/rescript-apollo-client/blob/master/EXAMPLES/src/hooksUsage/Query_Typical.res#L35).
Have you ever seen that?

Thanks for reading!

**Comment by jeddeloh** [comment]
I feel like someone might have posted this issue a long time ago on discord at a time when I didn't have time to look into it. I assumed they worked it out, but I guess not. We should look into what's going on.

**Comment by Laegel** [comment]
Thanks for your quick answer. I do have the fetch policy as `NetworkOnly` too... I'll try something else to verify your theory!

**Comment by jeddeloh** [comment]
Gonna close this for now. Please reopen if you can confirm this isn't the JS behavior. Thanks!
